# Generated by Django 5.0.2 on 2024-02-26 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Actor first name', max_length=60)),
                ('last_name', models.CharField(help_text='Actor last name', max_length=60)),
            ],
            options={
                'verbose_name': 'actor',
                'verbose_name_plural': 'actors',
                'db_table': 'actor',
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Director first name', max_length=60)),
                ('last_name', models.CharField(help_text='Director last name', max_length=60)),
            ],
            options={
                'verbose_name': 'director',
                'verbose_name_plural': 'directors',
                'db_table': 'director',
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Film name', max_length=60)),
                ('year_of_release', models.IntegerField(help_text='Film release year')),
                ('actors', models.ManyToManyField(help_text='List of actors', to='main.actor')),
                ('director', models.ForeignKey(help_text='Film director', on_delete=django.db.models.deletion.DO_NOTHING, to='main.director')),
            ],
            options={
                'verbose_name': 'film',
                'verbose_name_plural': 'films',
                'db_table': 'film',
            },
        ),
    ]
