# Generated by Django 5.0.2 on 2024-02-26 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='director',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='director',
            name='last_name',
        ),
        migrations.AddField(
            model_name='actor',
            name='name',
            field=models.CharField(default=None, help_text='Actor name', max_length=100),
        ),
        migrations.AddField(
            model_name='director',
            name='name',
            field=models.CharField(default=None, help_text='Director name', max_length=100),
        ),
    ]
